name: Build Wine tkg-ntsync (NoBootstrap)

on:
  workflow_dispatch:

env:
  WINE_BUILD_OPTIONS: "--without-ldap --without-oss --disable-winemenubuilder --disable-win16 --disable-test"
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install ccache
          sudo apt-get -y install gcc-multilib gcc-mingw-w64 libasound2-dev bluez libpulse-dev libdbus-1-dev libfontconfig-dev libfreetype-dev libgnutls28-dev libgl-dev libunwind-dev libx11-dev libxcomposite-dev libxcursor-dev libxfixes-dev libxi-dev libxrandr-dev libxrender-dev libxext-dev libwayland-bin libwayland-dev libegl-dev libxkbcommon-dev libxkbregistry-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libosmesa6-dev libsdl2-dev libudev-dev libvulkan-dev libv4l-dev
          sudo apt-get -y install libfontconfig-dev:i386 libfreetype-dev:i386 libgl-dev:i386 libunwind-dev:i386 libx11-dev:i386 libxcomposite-dev:i386 libxcursor-dev:i386 libxext-dev:i386 libwayland-bin:i386 libwayland-dev:i386 libegl-dev:i386 libsdl2-dev:i386 libvulkan-dev:i386 libosmesa6-dev:i386 libgnutls28-dev:i386 libgstreamer1.0-dev:i386 libgstreamer-plugins-base1.0-dev:i386
      - name: Pull Wine from kron4ek
        uses: actions/checkout@v4
        with:
          repository: Kron4ek/wine-tkg
          ref: ntsync
          path: ${{ github.workspace }}/wine
      - name: Build Wine (64)
        run: |
          cp -r ${{ github.workspace }}/wine ${{ github.workspace }}/wine-64
          cd ${{ github.workspace }}/wine-64
          ./configure --enable-win64 $WINE_BUILD_OPTIONS --prefix ${{ github.workspace }}/wine-amd64
          make -j$(nproc)
          cd ${{ github.workspace }}
      - name: Build Wine (32)
        run: |
          cp -r ${{ github.workspace }}/wine ${{ github.workspace }}/wine-32
          cd ${{ github.workspace }}/wine-32
          ./configure $WINE_BUILD_OPTIONS --with-wine64=${{ github.workspace }}/wine-64 --prefix ${{ github.workspace }}/wine-amd64
          make -j$(nproc)
          cd ${{ github.workspace }}
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/wine-amd64
